### ISSUE TITLE
Unable to run the demo

### ISSUE THREAD

**Issue by Zumbalamambo** [cvlab-epfl/detecting-the-unexpected#8]
when I tried to run the demo, I'm getting the following error

```

> [Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "<string>", line 1, in <module>
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     exitcode = _main(fd)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>     prepare(preparation_data)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>         _fixup_main_from_path(data['init_main_from_path'])_fixup_main_from_path(data['init_main_from_path'])
> 
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>         run_name="__mp_main__")run_name="__mp_main__")
> 
>   File "C:\Users\Anaconda3\lib\runpy.py", line 263, in run_path
>   File "C:\Users\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 85, in _run_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\demo.py", line 9, in <module>
>     exec(code, run_globals)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\demo.py", line 9, in <module>
>         joint_pipeline.init_gan()joint_pipeline.init_gan()
> 
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a05_differences\E1_article_evaluation.py", line 556, in init_gan
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a05_differences\E1_article_evaluation.py", line 556, in init_gan
>     self.pix2pix = Pix2PixHD_Generator()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 100, in __init__
>     self.pix2pix = Pix2PixHD_Generator()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 100, in __init__
>     self.mod_pix2pix = self.load_pix2pixHD_default(variant)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 93, in load_pix2pixHD_default
>     self.mod_pix2pix = self.load_pix2pixHD_default(variant)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 93, in load_pix2pixHD_default
>     pix2pixHD_module = create_model(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\models.py", line 15, in create_model
>     pix2pixHD_module = create_model(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\models.py", line 15, in create_model
>     model.initialize(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\pix2pixHD_model.py", line 40, in initialize
>     model.initialize(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\pix2pixHD_model.py", line 40, in initialize
>     opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids)        
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\networks.py", line 44, in define_G
>     opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids)        
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\networks.py", line 44, in define_G
>     netG.cuda(gpu_ids[0])
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
>     netG.cuda(gpu_ids[0])
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>     module._apply(fn)  File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
> 
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
>   [Previous line repeated 1 more time]
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
>     param_applied = fn(param)
>     param_applied = fn(param)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in <lambda>
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
>     return self._apply(lambda t: t.cuda(device))
> RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 563.35 MiB already allocated; 0 bytes free; 592.00 MiB reserved in total by PyTorch)
> RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 563.35 MiB already allocated; 0 bytes free; 592.00 MiB reserved in total by PyTorch)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\demo.py", line 9, in <module>
>     joint_pipeline.init_gan()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a05_differences\E1_article_evaluation.py", line 556, in init_gan
>     self.pix2pix = Pix2PixHD_Generator()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 100, in __init__
>     self.mod_pix2pix = self.load_pix2pixHD_default(variant)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 93, in load_pix2pixHD_default
>     pix2pixHD_module = create_model(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\models.py", line 15, in create_model
>     model.initialize(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\pix2pixHD_model.py", line 40, in initialize
>     opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids)        
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\networks.py", line 44, in define_G
>     netG.cuda(gpu_ids[0])
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
>     param_applied = fn(param)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
> RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 491.35 MiB already allocated; 0 bytes free; 520.00 MiB reserved in total by PyTorch)
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
>     exitcode = _main(fd)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 114, in _main
>     prepare(preparation_data)
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 225, in prepare
>     _fixup_main_from_path(data['init_main_from_path'])
>   File "C:\Users\Anaconda3\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
>     run_name="__mp_main__")
>   File "C:\Users\Anaconda3\lib\runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "C:\Users\Anaconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\demo.py", line 9, in <module>
>     joint_pipeline.init_gan()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a05_differences\E1_article_evaluation.py", line 556, in init_gan
>     self.pix2pix = Pix2PixHD_Generator()
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 100, in __init__
>     self.mod_pix2pix = self.load_pix2pixHD_default(variant)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\experiments.py", line 93, in load_pix2pixHD_default
>     pix2pixHD_module = create_model(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\models.py", line 15, in create_model
>     model.initialize(opt)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\pix2pixHD_model.py", line 40, in initialize
>     opt.n_blocks_local, opt.norm, gpu_ids=self.gpu_ids)        
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a04_reconstruction\pix2pixHD\models\networks.py", line 44, in define_G
>     netG.cuda(gpu_ids[0])
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
>     module._apply(fn)
>   [Previous line repeated 1 more time]
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
>     param_applied = fn(param)
>   File "C:\Users\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 304, in <lambda>
>     return self._apply(lambda t: t.cuda(device))
> RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 455.34 MiB already allocated; 4.90 MiB free; 484.00 MiB reserved in total by PyTorch)
> Traceback (most recent call last):
>   File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 761, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "C:\Users\Anaconda3\lib\multiprocessing\queues.py", line 105, in get
>     raise Empty
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:/Users/stanl/Documents/gan/detecting-the-unexpected/demo.py", line 13, in <module>
>     joint_pipeline.run_on_dset(dset, b_show=True)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\a05_differences\E1_article_evaluation.py", line 668, in run_on_dset
>     pipe.execute(dset, b_one_batch=True, **exec_kwargs)
>   File "C:\Users\Documents\gan\detecting-the-unexpected\src\pipeline\pipeline.py", line 159, in execute
>     for loader_item in loader:
>   File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 841, in _next_data
>     idx, data = self._get_data()
>   File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 808, in _get_data
>     success, data = self._try_get_data()
>   File "C:\Users\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 774, in _try_get_data
>     raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
> RuntimeError: DataLoader worker (pid(s) 12572, 15572, 8680, 10208) exited unexpectedly](url)

```

**Comment by adynathos** [comment]
> RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 4.00 GiB total capacity; 563.35 MiB already allocated; 0 bytes free; 592.00 MiB reserved in total by PyTorch)

Looks like the GPU memory is full.
Perhaps you can try a smaller batch size [joint_pipeline.set_batch_size](https://github.com/cvlab-epfl/detecting-the-unexpected/blob/master/src/a05_differences/E1_article_evaluation.py#L537)
